ACCESS_TOKEN_PRIVATE_KEY_PATH: "/build/access-refresh-token-keys/access-token-private.key"
ACCESS_TOKEN_PUBLIC_KEY_PATH: "/build/access-refresh-token-keys/access-token-public.key"
REFRESH_TOKEN_PRIVATE_KEY_PATH: "/build/access-refresh-token-keys/refresh-token-private.key"
REFRESH_TOKEN_PUBLIC_KEY_PATH: "/build/access-refresh-token-keys/refresh-token-public.key"
MYSQL_USERNAME: "mbet"
MYSQL_PASSWORD: "t#LhO|x[U}77GoU.T|#r)*c322cB"
MYSQL_HOST: "localhost"
MYSQL_PORT: '3306'
MYSQL_DB: "pg_mbet"
MYSQL_TIMEZONE: "Africa/Dar_es_Salaam"