port 6383
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-announce-ip 172.28.0.15
cluster-announce-port 6379
cluster-announce-bus-port 16383
maxmemory 1gb
maxmemory-policy allkeys-lru
appendonly yes
requirepass "S*^%PuR0xK!3pT@sWq<="
masterauth "S*^%PuR0xK!3pT@sWq<="
protected-mode yes
dir /data