port 6379
cluster-enabled yes
cluster-config-file nodes.conf
cluster-node-timeout 5000
cluster-announce-ip 172.28.0.11
cluster-announce-port 6379
cluster-announce-bus-port 16379
maxmemory 1gb
maxmemory-policy allkeys-lru
appendonly yes
requirepass Si*%PuR=!xK!3pT@sWq<=>
masterauth Si*%PuR=!xK!3pT@sWq<=>
protected-mode yes
dir /data