package com.hybrid9.pg.Lipanasi.enums;

public enum RequestStatus {
    NEW,
    INITIATED,
    COMPLETED,
    FAILED,
    DUPLICATE, NETWORK_CONNECTION_ISSUE, OPERATOR_ERROR_RESPONSE,
    MARKED_FOR_RETRY,
    SERVICE_UNAVAILABLE,
    INVALID_CREDENTIALS,
    TIMEOUT,
    INVALID_REQUEST,
    BUSINESS_RULE_VIOLATION,
    RESOURCE_NOT_FOUND
}
